[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224
    Tag         app.logs

[FILTER]
    Name        parser
    Match       app.logs
    Key_Name    log
    Parser      json
    Reserve_Data true

[OUTPUT]
    Name        stdout
    Match       *
